### ISSUE TITLE
Idea: how about save every `chatgpt-arcana-start-chat' sesstion as a file?

### ISSUE THREAD

**Issue by randomwangran** [CarlQLange/chatgpt-arcana.el#1]
Next time, you want to start a new session, the prompt can remember your previous talk. Just like the interface with Org-roam.

**Comment by CarlQLange** [comment]
Already got there I think! https://github.com/CarlQLange/chatgpt-arcana.el/commit/9cbfd355581615661714faf024e73bd34a4deeba

I guess a `chatgpt-arcana-chat-continue-previous-chat` might be worth adding.
