### ISSUE TITLE
How to send second user message on chat?

### ISSUE THREAD

**Issue by kamushadenes** [CarlQLange/chatgpt-arcana.el#11]
Hello there!

I'm new to Emacs and I'm having a hard time sending a second message to the same chat.

![image](https://github.com/CarlQLange/chatgpt-arcana.el/assets/242529/76d79f68-8e98-4cff-a3af-b091a8ff7253)

I tried `Enter`, `Ctrl+Enter` and some other stuff but that didn't work.

Sorry for the newbie question, thank you!

**Comment by CarlQLange** [comment]
Ah, [it's control-C control-C by default](https://github.com/CarlQLange/chatgpt-arcana.el/blob/master/chatgpt-arcana.el#L195) :)

**Comment by kamushadenes** [comment]
Thank you!
