### ISSUE TITLE
Streaming Mode

### ISSUE THREAD

**Issue by kamushadenes** [CarlQLange/chatgpt-arcana.el#12]
This project is amazing! It alone made me give Emacs another try, congratulations!

I have a question. It sometimes take a long time to generate responses, especially when using GPT-4. Of course this is OpenAI related, but the "developer experience" is affected.

Any chance we can implement OpenAI's streaming mode? I understand it might be very complex, but do you believe it's at least feasible in Emacs?

Thanks!

**Comment by CarlQLange** [comment]
Yes, I was thinking about it. Some other emacs ChatGPT packages do implement this as far as I know, but I personally don't have the lisp-fu to do it, unfortunately :)
