### ISSUE TITLE
Non-Doom user

### ISSUE THREAD

**Issue by randomwangran** [CarlQLange/chatgpt-arcana.el#2]
Is there any walkaround for this snippet?

https://github.com/CarlQLange/chatgpt-arcana.el/blob/dad91e4da6bddd0ae1e4fff840ff0b8e1f49f8e2/chatgpt-arcana.el#LL439-L439C14

**Comment by CarlQLange** [comment]
Yes, sorry, that should be in my personal config. Sorry, I will remove it later!

**Comment by CarlQLange** [comment]
Removed :)
