### ISSUE TITLE
Choice for concise title

### ISSUE THREAD

**Issue by randomwangran** [CarlQLange/chatgpt-arcana.el#3]
Right now, it is like:

`what-makes-a-good-talk-and-how-to-generate-a-concise-title.chatgpt-arcana.md`

How about making it into:

`what-makes-a-good-talk...`

Similar to left column on ai.com

**Comment by CarlQLange** [comment]
Regarding the concise title, you can modify the prompt that's used to generate the buffer name with `chatgpt-arcana-generated-buffer-name-prompt`. Feel free to experiment and find one that'll generate a better name. This is actually one of the prompts I've struggled the most with myself, it doesn't work as well as I would like.

I like the idea of a dedicated frame and so on. I will probably do something similar but likely in my own config for the package. If you implement it yourself I'd be interested to see it!

**Comment by CarlQLange** [comment]
I added a better default prompt for generating buffer names that only fails maybe one in five times. The downside is that it uses quite a few tokens. Tricky to come up with the best ones - I guess someone will need to write some kind of evaluation framework for prompt engineering.

I don't use org-roam unfortunately, but you might find this alternative package useful: https://github.com/rksm/org-ai

Thanks for your interest in the package :)
