### ISSUE TITLE
read the key value from .authinfo or some equivalent instead of init file

### ISSUE THREAD

**Issue by vxe** [CarlQLange/chatgpt-arcana.el#8]
I'm doing something like

```
(setq chatgpt-arcana-api-key (auth-source-pick-first-password
                                              :host "chat.openai.com"))
```

with an `~/.authinfo` that looks like

```
machine chat.openai.com login CHATGPT_EMAIL password API_KEY
```

so i don't accidentally make my key publicly available.  great package btw, really enjoying the user experience

**Comment by CarlQLange** [comment]
That's a great idea, it would never have occurred to me. I will probably add this as instructions to the readme rather than the package itself.

Glad you like the package!
